clientUrl: 127.0.0.1
eurekaUrl: http://admin:loyer.@127.0.0.1:9000/eureka/eureka/
databaseUrl: 139.198.188.135
oracleUrl: 127.0.0.1
serverUrl: 49.234.53.243
vsFtpdUrl: ${serverUrl}
swaggerUrl: loyer.com:9010